##
# DoIt subroutes
-
  name: 'Static Route'
  uriPattern: 'doit'
  defaults:
    '@package':    'Toko.Doit'
    '@controller': 'Task'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Dynamic Routes'
  uriPattern: 'doit/{@action}'
  defaults:
    '@package':    'Toko.Doit'
    '@controller': 'Task'
    '@format':     'html'
